const Sequelize = require('sequelize');
const sequelize = require('../util/database');

const Move = sequelize.define('moves', {
  id: {
    type: Sequelize.INTEGER,
    allowNull: false,
    autoIncrement: true,
    primaryKey: true
  },
  first_name: Sequelize.STRING,
  last_name: Sequelize.STRING,
  phone: Sequelize.STRING,
  email: Sequelize.STRING,
  passcode: Sequelize.STRING,
  rate: Sequelize.INTEGER,
  crew_size: Sequelize.INTEGER,
  truck_number: Sequelize.INTEGER,
  travel_time: Sequelize.FLOAT,
  deposit: Sequelize.INTEGER,
  origin_address: Sequelize.STRING,
  origin_address2: Sequelize.STRING,
  origin_city: Sequelize.STRING,
  origin_state: Sequelize.STRING,
  origin_zipcode: Sequelize.STRING,
  destination_address: Sequelize.STRING,
  destination_address2: Sequelize.STRING,
  destination_city: Sequelize.STRING,
  destination_state: Sequelize.STRING,
  destination_zipcode: Sequelize.STRING,
  signature1_url: Sequelize.STRING,
  signature1_hash: Sequelize.STRING,
  signature1_datetime: Sequelize.DATE,
  move_date: Sequelize.DATEONLY,
  start_time: Sequelize.TIME,
  end_time: Sequelize.TIME,
  break_time: Sequelize.STRING,
  b15: Sequelize.INTEGER,
  b30: Sequelize.INTEGER,
  b45: Sequelize.INTEGER,
  b60: Sequelize.INTEGER,
  mirror: Sequelize.INTEGER,
  dishpack: Sequelize.INTEGER,
  mattress: Sequelize.INTEGER,
  tape: Sequelize.INTEGER,
  bubble: Sequelize.INTEGER,
  signature2_url: Sequelize.STRING,
  signature2_hash: Sequelize.STRING,
  signature2_datetime: Sequelize.DATE,
  packingmaterials: Sequelize.FLOAT,
  labor_time: Sequelize.FLOAT,
  subtotal: Sequelize.FLOAT,
  subtotalcc: Sequelize.FLOAT,
  createdAt: Sequelize.DATE,
  updatedAt: Sequelize.DATE,
  signatures_ip: Sequelize.STRING,
  document_id: Sequelize.STRING,
  email_changed: Sequelize.STRING,
  phone_changed: Sequelize.STRING,
  email_changed: Sequelize.STRING,
  bol_number: Sequelize.STRING,
  estimated_hrs: Sequelize.STRING,
  estimated_packing: Sequelize.STRING,
  signature3_url: Sequelize.STRING,
  signature3_hash: Sequelize.STRING,
  signature3_datetime: Sequelize.DATE
  

});

module.exports = Move;

